security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9999/revo-auth-service/user
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://revo-eureka-server:revo-eureka-server-password@localhost:8761/eureka/